tunnel: ffc8edf6-0dd3-4bea-b7bb-99774355eed6
credentials-file: /etc/cloudflared/credentials.json

ingress:
  - hostname: amttp.com
    service: http://nginx-gateway:80
    originRequest:
      connectTimeout: 30s
      noTLSVerify: true

  - hostname: www.amttp.com
    service: http://nginx-gateway:80
    originRequest:
      connectTimeout: 30s
      noTLSVerify: true

  # Catch-all (required by cloudflared)
  - service: http_status:404
