import paramiko, sys

ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh.connect('194.35.120.52', username='root', password='DZc3n0IetkN6BQKwn35EPO8gm57S', timeout=10)

env_content = """# AMTTP Production — Contabo VPS
# Generated by deploy script

# MongoDB
MONGO_INITDB_ROOT_USERNAME=admin
MONGO_INITDB_ROOT_PASSWORD=AmTTp_M0ng0_2026_Pr0d

# Redis
REDIS_PASSWORD=AmTTp_R3d1s_2026_Pr0d

# MinIO
MINIO_ROOT_USER=minioadmin
MINIO_ROOT_PASSWORD=AmTTp_M1n10_2026_Pr0d

# Grafana
GF_SECURITY_ADMIN_PASSWORD=AmTTp_Gr4f_2026

# Cloudflare tunnel token (set this after creating tunnel)
CLOUDFLARE_TUNNEL_TOKEN=

# Domain
DOMAIN=amttp.com

# Dashboard
MONGODB_URL=mongodb://mongo:27017
DOCKER_CONTAINER=true
ORCHESTRATOR_URL=http://orchestrator:8007
"""

# Write .env
_, stdout, stderr = ssh.exec_command(f"cat > /opt/amttp/.env << 'ENVEOF'\n{env_content}\nENVOF")
stdout.read()

# Verify
_, stdout, _ = ssh.exec_command("wc -l /opt/amttp/.env; chmod 600 /opt/amttp/.env; chown amttp:amttp /opt/amttp/.env; echo ENV_OK")
print(stdout.read().decode())

ssh.close()
